name: product
description: "A new Flutter package for product."
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Shared packages
  core:
    path: ../../shared/core
  design_system:
    path: ../../shared/design_system
  session:
    path: ../../shared/session

  # Infrastructure packages
  network:
    path: ../../infrastructure/network
  event_bus:
    path: ../../infrastructure/event_bus

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: any
  freezed: any
  json_serializable: any
  injectable_generator: any
  auto_route_generator: any

  # Testing
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

