name: flutter_modular_clean_architecture
description: A new Flutter project demonstrating modular and clean architecture principles.
workspace:
  - packages/shared/network
  - packages/shared/config
  - packages/features/auth

environment:
  sdk: ^3.9.2

dev_dependencies:
  melos: ^7.1.1

melos:
  command:
    bootstrap:
      # It seems so that running "pub get" in parallel has some issues (like
      # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
      # makes the CI much more stable.
      runPubGetInParallel: false
      
  scripts:
    codegen:
      run: |
        melos exec --fail-fast -- \
          "dart run build_runner build --delete-conflicting-outputs"
      description: Run code generation for all packages.
      packageFilters:
        dependsOn:
          - build_runner
        dirExists:
          - lib
    codegen:watch:
      run: |
        melos exec --fail-fast -- \
          "dart run build_runner watch --delete-conflicting-outputs"
      description: Run code generation in watch mode for all packages.
      packageFilters:
        dependsOn:
          - build_runner
        dirExists:
          - lib
    test:
      run: |
        melos exec --fail-fast -- \
          "flutter test"
      description: Run `flutter test` for a specific package.
      packageFilters:
        dirExists:
          - test
        ignore:
          - '*example*'