name: assets
description: "A new Flutter package project."
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_gen: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  flutter_gen_runner: ^5.12.0

flutter:
  assets:
    - assets/images/

flutter_gen:
  output: lib/gen/
