// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;

import 'src/models/auth/auth_token_db_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 2712729777245706162),
    name: 'AuthTokenDbModel',
    lastPropertyId: const obx_int.IdUid(7, 3423645180672015746),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4997390862191643862),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2734880067869259978),
        name: 'accessToken',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5661381484644790081),
        name: 'refreshToken',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3649255620903566131),
        name: 'issuedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3423645180672015746),
        name: 'expiresIn',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
obx.Store openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) {
  return obx.Store(
    getObjectBoxModel(),
    directory: directory,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 2712729777245706162),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [954082925542205174, 8904617148721647372],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AuthTokenDbModel: obx_int.EntityDefinition<AuthTokenDbModel>(
      model: _entities[0],
      toOneRelations: (AuthTokenDbModel object) => [],
      toManyRelations: (AuthTokenDbModel object) => {},
      getId: (AuthTokenDbModel object) => object.id,
      setId: (AuthTokenDbModel object, int id) {
        object.id = id;
      },
      objectToFB: (AuthTokenDbModel object, fb.Builder fbb) {
        final accessTokenOffset = fbb.writeString(object.accessToken);
        final refreshTokenOffset = fbb.writeString(object.refreshToken);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(3, accessTokenOffset);
        fbb.addOffset(4, refreshTokenOffset);
        fbb.addInt64(5, object.issuedAt.millisecondsSinceEpoch);
        fbb.addInt64(6, object.expiresIn);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final accessTokenParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final issuedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final expiresInParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final object =
            AuthTokenDbModel(
                accessToken: accessTokenParam,
                issuedAt: issuedAtParam,
                expiresIn: expiresInParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..refreshToken = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGet(buffer, rootOffset, 12, '');

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AuthTokenDbModel] entity fields to define ObjectBox queries.
class AuthTokenDbModel_ {
  /// See [AuthTokenDbModel.id].
  static final id = obx.QueryIntegerProperty<AuthTokenDbModel>(
    _entities[0].properties[0],
  );

  /// See [AuthTokenDbModel.accessToken].
  static final accessToken = obx.QueryStringProperty<AuthTokenDbModel>(
    _entities[0].properties[1],
  );

  /// See [AuthTokenDbModel.refreshToken].
  static final refreshToken = obx.QueryStringProperty<AuthTokenDbModel>(
    _entities[0].properties[2],
  );

  /// See [AuthTokenDbModel.issuedAt].
  static final issuedAt = obx.QueryDateProperty<AuthTokenDbModel>(
    _entities[0].properties[3],
  );

  /// See [AuthTokenDbModel.expiresIn].
  static final expiresIn = obx.QueryIntegerProperty<AuthTokenDbModel>(
    _entities[0].properties[4],
  );
}
