name: profile
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
    
  # Internal packages
  core:
    path: ../../shared/core
  event_bus:
    path: ../../shared/event_bus

dev_dependencies:
  auto_route_generator: ^10.2.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  injectable_generator: ^2.8.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1